#! /bin/sh

sudo udevadm control --reload-rules && sudo udevadm trigger
exit

# For testing:
udevadm test /sys/bus/usb/devices/1-1.2.4
udevadm test /sys/bus/usb/devices/1-1.2.4.3
udevadm test /sys/bus/usb/devices/1-1.2.4.3:1.0

